#include <stdio.h>
#include "openssl/evp.h"
#include <string.h>

#define MAX_LENGTH 16 // A global variable t define max-length

int main (int argc, const char *argv[])
{
	/* This variable is used to store the ciphertext provided to you. Make sure to use the proper format, eg. the hex 'd23a' would be written as {0xd2,0x3a} in C */
	unsigned char ciphertxt[] = {0x00};

	// This is the plaintext that we are encrypting. Do not change it as it may result in a different ciphertext
	char plaintext[]= "This is a top secret";

	// Pointer fp used to point to the English words file provided along.
	FILE *fp;

	// The initialization Vector is set to 0
	unsigned char iv[] = {0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00};

	// Output buffer set to 1024 size
	unsigned char outbuf [1024];

	// Some other variables that are used in the program
	int outlen = 0, tmplen = 0;
	/* You may want to declare some additional variables to be used as flags*/

	EVP_CIPHER_CTX ctx;

	if (/* Use this statement to check is the words.txt file can be opened in 'r' permission */)
	{
		/* Print a statement if the above condition is not met */
		return 0;
	}

	char key [MAX_LENGTH]; //array to store the key getting from the dictionary

	while (fgets(key, MAX_LENGTH, fp) != NULL)
	{
		for(int i = 0; i < MAX_LENGTH; i++)
		{
			if (key[i] == '\n' || key[i] == 0 ) //when key is less than 16 characters, the extra left part is filled with " "
			{
				for (int j = i; j < strlen(key); j++)
				{
					key[j] = ' ';
				}
				break;
			}
		}

		// Use the EVP library to initialize cipher
		EVP_CIPHER_CTX_init (&ctx);

		// Use the EVP library to encrypt the cipher
		EVP_EncryptInit_ex (&ctx, EVP_aes_128_cbc(), NULL, key, iv);

		// Checking to see if EVP_EncryptUpdate is valid or not
		if (!EVP_EncryptUpdate (&ctx, outbuf, &outlen, plaintext, strlen(plaintext)))
		{
			/*Print Out a relevant Error Messege*/
			return 0;
		}

		// Buffer passed to EVP_EncryptFinal() must be after data just encrypted to avoid overwriting it

		// Checking to see if !EVP_EncryptFinal_ex is valid or not
		if (!EVP_EncryptFinal_ex (&ctx, outbuf + outlen, &tmplen))
		{
			/*Print Out a relevant Error Messege*/
			return 0;
		}

		outlen += tmplen;

		EVP_CIPHER_CTX_cleanup (&ctx);

		//print curret key and its corresponding ciphertext
		printf ("The key is : %s       The Corresponding Cipher Text Is:  ", key); 

		for(int j = 0; j < outlen; j++) 
		{
			/* Use a loop to print out the buffer */
		}
		printf ("\n");

		for(int q = 0; q < outlen; q++)
		{
			/* Judge whether the cipher text generated by this key is match for the provoded one */
			/* As the whole ciphertext cannot be matched at once, use this loop to match it bit by bit */
		}

		if (/* If the generated ciphertext matched with the one provided*/)
		{
			printf ("\n*****************************************************\n");

			/* Print the key used */

			/* Print the text in the buffer */

			/* Print the provided ciphertext*/

			/* Print the length of the ciphertext */

			printf ("\n*****************************************************\n");
			return 0;
		}
	}
	fclose (fp);
	return 0;
}
